namespace ChildCare.Application.Common;

/// <summary>
/// Signed-URL port for a contract's final signed PDF (feature 024-esignature, research.md R6).
/// Mirrors IFiscalAttestationStorage's shape exactly (server-generated bytes written directly,
/// no client-signed upload). Immutability (FR-010 — never regenerated after signing) is enforced
/// at the application layer: SubmitContractSigningCommandHandler only ever calls UploadAsync once
/// per contract, gated by the same atomic single-use signing-token check that already prevents a
/// second successful submission — this port does not self-enforce write-once semantics, matching
/// every existing Gcs*Storage port in this codebase.
/// </summary>
public interface ISignedContractStorage
{
    /// <summary>Writes the PDF to a deterministic object path keyed on contractId.</summary>
    Task<string> UploadAsync(Guid contractId, byte[] pdfBytes, CancellationToken cancellationToken = default);

    Task<string> CreateDownloadUrlAsync(string objectPath, CancellationToken cancellationToken = default);
}
