using ChildCare.Application.Common;
using Google.Apis.Auth.OAuth2;
using Google.Cloud.Storage.V1;
using Microsoft.Extensions.Configuration;

namespace ChildCare.Infrastructure.Storage;

/// <summary>
/// ISignedContractStorage implementation (feature 024-esignature, research.md R6) — mirrors
/// GcsFiscalAttestationStorage exactly (server-generated bytes written directly, no
/// client-signed upload; reuses the existing "Storage:ProfilePhotosBucketName" bucket under a
/// "signed-contracts/" path prefix — same bucket-reuse-via-prefix precedent as every other
/// Gcs*Storage port, no new bucket/Terraform change). Immutability is an application-layer
/// guarantee (single-use signing token), not enforced here — see the interface's doc comment.
/// </summary>
public class GcsSignedContractStorage : ISignedContractStorage
{
    private static readonly TimeSpan DownloadUrlDuration = TimeSpan.FromMinutes(15);

    private readonly string _bucketName;
    private readonly Lazy<Task<StorageClient>> _storageClient;
    private readonly Lazy<Task<UrlSigner>> _urlSigner;

    public GcsSignedContractStorage(IConfiguration config)
    {
        _bucketName = config["Storage:ProfilePhotosBucketName"]
            ?? throw new InvalidOperationException("Storage:ProfilePhotosBucketName is not configured.");

        _storageClient = new Lazy<Task<StorageClient>>(async () =>
        {
            var credential = await GoogleCredential.GetApplicationDefaultAsync();
            return await StorageClient.CreateAsync(credential);
        });

        _urlSigner = new Lazy<Task<UrlSigner>>(async () =>
        {
            var credential = await GoogleCredential.GetApplicationDefaultAsync();
            return UrlSigner.FromCredential(credential);
        });
    }

    public async Task<string> UploadAsync(Guid contractId, byte[] pdfBytes, CancellationToken cancellationToken = default)
    {
        var objectPath = $"signed-contracts/{contractId}.pdf";

        var client = await _storageClient.Value;
        using var stream = new MemoryStream(pdfBytes);
        await client.UploadObjectAsync(_bucketName, objectPath, "application/pdf", stream, cancellationToken: cancellationToken);

        return objectPath;
    }

    public async Task<string> CreateDownloadUrlAsync(string objectPath, CancellationToken cancellationToken = default)
    {
        var signer = await _urlSigner.Value;
        return await signer.SignAsync(_bucketName, objectPath, DownloadUrlDuration, cancellationToken: cancellationToken);
    }
}
